[functions.health]
enabled = true
verify_jwt = false
import_map = "./functions/deno.json"
entrypoint = "./functions/health/index.ts"

[functions.api]
enabled = true
verify_jwt = false
import_map = "./functions/deno.json"
entrypoint = "./functions/api/index.ts"